/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Bernd' at '08.05.17 10:34' with Gradle 2.14.1
 *
 * @author Bernd, @date 08.05.17 10:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
