/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Bernd' at '10.05.17 12:08' with Gradle 2.14.1
 *
 * @author Bernd, @date 10.05.17 12:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
