/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Bernd' at '14.05.17 21:48' with Gradle 2.14.1
 *
 * @author Bernd, @date 14.05.17 21:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
